language: python
dist: bionic
matrix:
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - python: 3.5
      dist: xenial
notifications:
  email: false
install: pip install tox-travis
script: tox
